Lesson4
osipovichka/Blog pull request #2
Opened 2020-10-02 18:56 UTC by osipovichka

2020-10-03 14:50 UTC, osipovik requested changes

2020-10-03 14:50 UTC, osipovik commented on src/main/java/com/example/blog/controllers/BlogController.java
> +    private  PostRepository postRepository;
remove extra space after modificator

2020-10-03 14:50 UTC, osipovik commented on src/main/java/com/example/blog/models/Post.java
> +    private String title, anons, full_text;
Split declaration on separate lines

2020-10-03 14:50 UTC, osipovik commented on src/main/java/com/example/blog/models/Post.java
> +    private String title, anons, full_text;
rename `full_text` using camel case

2020-10-03 14:50 UTC, osipovik commented on src/main/java/com/example/blog/models/Post.java
> +    private String title, anons, full_text;
Add `lombok` to project

2020-10-05 09:43 UTC, osipovichka commented on src/main/java/com/example/blog/controllers/BlogController.java
> +    private  PostRepository postRepository;
done sir

2020-10-05 09:43 UTC, osipovichka commented on src/main/java/com/example/blog/models/Post.java
> +    private String title, anons, full_text;
done sir

2020-10-05 10:16 UTC, merged